python ../main.py  > log 2> error
